package view;

import java.math.BigDecimal;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Avaliacao;
import model.AvaliacaoDao;
import model.TableModelAvaliacao;
import util.TextFieldsUtils;

public class CrudAvaliacoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrudPessoas
     */
    private TableModelAvaliacao tableModelAvaliacao;
    public CrudAvaliacoes(Connection con) {
         connection = con;
         avaliacoesDao = new AvaliacaoDao(con);
        initComponents();
        tableModelAvaliacao = new TableModelAvaliacao();
        this.tabelasAvaliacoes.setModel(tableModelAvaliacao);
        adicionaElementos();
    }
     public void adicionaElementos(){
         List<Avaliacao> listaAvaliacao = this.avaliacoesDao.getLista();
         for (Avaliacao avaliacao : listaAvaliacao) {
             tableModelAvaliacao.addAvaliacao(avaliacao);
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        jLabelId2 = new javax.swing.JLabel();
        tfTrabalho = new javax.swing.JTextField();
        tfAvaliador = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelId3 = new javax.swing.JLabel();
        jLabelId4 = new javax.swing.JLabel();
        tfCriterio1 = new javax.swing.JTextField();
        tfCriterio2 = new javax.swing.JTextField();
        jLabelId5 = new javax.swing.JLabel();
        jLabelId6 = new javax.swing.JLabel();
        jLabelId7 = new javax.swing.JLabel();
        jLabelId8 = new javax.swing.JLabel();
        jLabelId9 = new javax.swing.JLabel();
        jLabelId10 = new javax.swing.JLabel();
        jLabelId11 = new javax.swing.JLabel();
        jLabelId12 = new javax.swing.JLabel();
        jLabelId13 = new javax.swing.JLabel();
        jLabelId14 = new javax.swing.JLabel();
        jLabelId15 = new javax.swing.JLabel();
        jLabelId16 = new javax.swing.JLabel();
        tfCriterio3 = new javax.swing.JTextField();
        tfCriterio4 = new javax.swing.JTextField();
        tfCriterio5 = new javax.swing.JTextField();
        tfCriterio6 = new javax.swing.JTextField();
        tfCriterio7 = new javax.swing.JTextField();
        tfCriterio8 = new javax.swing.JTextField();
        tfCriterio9 = new javax.swing.JTextField();
        tfCriterio10 = new javax.swing.JTextField();
        tfCriterio11 = new javax.swing.JTextField();
        tfCriterio12 = new javax.swing.JTextField();
        tfCriterio13 = new javax.swing.JTextField();
        tfCriterio14 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelasAvaliacoes = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabelId18 = new javax.swing.JLabel();
        tfPeriodo = new javax.swing.JTextField();
        jLabelId19 = new javax.swing.JLabel();
        tfDataAvaliacao = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(240, 240, 250));
        jPanel1.setAutoscrolls(true);

        jLabel9.setBackground(new java.awt.Color(235, 240, 240));
        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Avaliações");

        jLabelId.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId.setText("      ID:");

        tfId.setEditable(false);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabelId1.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId1.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId1.setText("TRABALHO");

        jLabelId2.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId2.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId2.setText("AVALIADOR");

        tfTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTrabalhoActionPerformed(evt);
            }
        });

        tfAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAvaliadorActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");

        jLabel4.setBackground(new java.awt.Color(250, 240, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOTAS");

        jLabelId3.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId3.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId3.setText("CRITÉRIO 1");

        jLabelId4.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId4.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId4.setText("CRITÉRIO 2");

        tfCriterio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio1ActionPerformed(evt);
            }
        });

        tfCriterio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio2ActionPerformed(evt);
            }
        });

        jLabelId5.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId5.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId5.setText("CRITÉRIO 3");

        jLabelId6.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId6.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId6.setText("CRITÉRIO 4");

        jLabelId7.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId7.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId7.setText("CRITÉRIO 6");

        jLabelId8.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId8.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId8.setText("CRITÉRIO 5");

        jLabelId9.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId9.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId9.setText("CRITÉRIO 7");

        jLabelId10.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId10.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId10.setText("CRITÉRIO 8");

        jLabelId11.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId11.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId11.setText("CRITÉRIO 9");

        jLabelId12.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId12.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId12.setText("CRITÉRIO 10");

        jLabelId13.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId13.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId13.setText("CRITÉRIO 11");

        jLabelId14.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId14.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId14.setText("CRITÉRIO 12");

        jLabelId15.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId15.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId15.setText("CRITÉRIO 13");

        jLabelId16.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId16.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId16.setText("CRITÉRIO 14");

        tfCriterio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio3ActionPerformed(evt);
            }
        });

        tfCriterio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio4ActionPerformed(evt);
            }
        });

        tfCriterio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio5ActionPerformed(evt);
            }
        });

        tfCriterio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio6ActionPerformed(evt);
            }
        });

        tfCriterio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio7ActionPerformed(evt);
            }
        });

        tfCriterio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio8ActionPerformed(evt);
            }
        });

        tfCriterio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio9ActionPerformed(evt);
            }
        });

        tfCriterio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio10ActionPerformed(evt);
            }
        });

        tfCriterio11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio11ActionPerformed(evt);
            }
        });

        tfCriterio12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio12ActionPerformed(evt);
            }
        });

        tfCriterio13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio13ActionPerformed(evt);
            }
        });

        tfCriterio14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCriterio14ActionPerformed(evt);
            }
        });

        tabelasAvaliacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelasAvaliacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelasAvaliacoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelasAvaliacoes);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabelId18.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId18.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId18.setText("PERIODO:");

        tfPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPeriodoActionPerformed(evt);
            }
        });

        jLabelId19.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId19.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId19.setText("DATA AVALIAÇÃO:");

        tfDataAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCriterio13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAdicionar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabelId16))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfCriterio11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelId14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfCriterio7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelId10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfCriterio5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelId7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfCriterio3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelId6))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfCriterio1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelId11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfCriterio9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelId3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelId4)
                                        .addComponent(jLabelId12))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCriterio14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelId)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelId1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelId19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelId18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtualizar)
                            .addComponent(btnDeletar)
                            .addComponent(btnFechar))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId)
                                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelId2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelId1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDataAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCriterio12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelId15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCriterio13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCriterio14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnLimpar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTrabalhoActionPerformed

    private void tfAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAvaliadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAvaliadorActionPerformed

    private void tfCriterio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio1ActionPerformed

    private void tfCriterio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio2ActionPerformed

    private void tfCriterio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio3ActionPerformed

    private void tfCriterio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio4ActionPerformed

    private void tfCriterio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio5ActionPerformed

    private void tfCriterio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio6ActionPerformed

    private void tfCriterio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio7ActionPerformed

    private void tfCriterio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio8ActionPerformed

    private void tfCriterio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio9ActionPerformed

    private void tfCriterio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio10ActionPerformed

    private void tfCriterio11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio11ActionPerformed

    private void tfCriterio12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio12ActionPerformed

    private void tfCriterio13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio13ActionPerformed

    private void tfCriterio14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCriterio14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCriterio14ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        new TextFieldsUtils().clearTextFields(rootPane);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        List <String> strings = new ArrayList<String>();
        new TextFieldsUtils().getTfs(rootPane, strings);
        if (new TextFieldsUtils().verificandoVazios(strings)) {
            JOptionPane.showMessageDialog(this, "Campos vazios");
        } else {
            try {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                Avaliacao novaAvaliacao = new Avaliacao();
                  if(tfId.getText().equals("") == false){
                    novaAvaliacao.setId(Long.parseLong(tfId.getText()));
                }
                novaAvaliacao.setTrabalhoAvaliado(Integer.parseInt(this.tfTrabalho.getText()));
                novaAvaliacao.setAvaliador(Integer.parseInt(this.tfAvaliador.getText()));
                novaAvaliacao.setPeriodo(this.tfPeriodo.getText());
                novaAvaliacao.setDataAvaliacao(LocalDate.parse(this.tfDataAvaliacao.getText(),dtf));
                novaAvaliacao.setNotaCriterio1(new BigDecimal(this.tfCriterio1.getText()));
                novaAvaliacao.setNotaCriterio2(new BigDecimal(this.tfCriterio2.getText()));
                novaAvaliacao.setNotaCriterio3(new BigDecimal(this.tfCriterio3.getText()));
                novaAvaliacao.setNotaCriterio4(new BigDecimal(this.tfCriterio4.getText()));
                novaAvaliacao.setNotaCriterio5(new BigDecimal(this.tfCriterio5.getText()));
                novaAvaliacao.setNotaCriterio6(new BigDecimal(this.tfCriterio6.getText()));
                novaAvaliacao.setNotaCriterio7(new BigDecimal(this.tfCriterio7.getText()));
                novaAvaliacao.setNotaCriterio8(new BigDecimal(this.tfCriterio8.getText()));
                novaAvaliacao.setNotaCriterio9(new BigDecimal(this.tfCriterio9.getText()));
                novaAvaliacao.setNotaCriterio10(new BigDecimal(this.tfCriterio10.getText()));
                novaAvaliacao.setNotaCriterio11(new BigDecimal(this.tfCriterio11.getText()));
                novaAvaliacao.setNotaCriterio12(new BigDecimal(this.tfCriterio12.getText()));
                novaAvaliacao.setNotaCriterio13(new BigDecimal(this.tfCriterio13.getText()));
                novaAvaliacao.setNotaCriterio14(new BigDecimal(this.tfCriterio14.getText()));
                if(avaliacoesDao.salvar(novaAvaliacao)){
                if(novaAvaliacao.getId() == null){
                      novaAvaliacao.setId(avaliacoesDao.getLista().get(avaliacoesDao.getLista().size()-1).getId());
                    tableModelAvaliacao.addAvaliacao(novaAvaliacao);
                }  else { 
                    tableModelAvaliacao.edita(novaAvaliacao);
                }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Campos Informados Incorretamente");
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tfPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPeriodoActionPerformed

    private void tfDataAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataAvaliacaoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(tfId.getText() == ""){
            JOptionPane.showMessageDialog(this, "Id vazio");
        } else{
            if(avaliacoesDao.removeAvaliacao(Long.parseLong(this.tfId.getText()))){
                tableModelAvaliacao.removerAvaliacao(tabelasAvaliacoes.getSelectedRow());
                 new TextFieldsUtils().clearTextFields(rootPane);
            }
            
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tabelasAvaliacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelasAvaliacoesMouseClicked
         int linha = this.tabelasAvaliacoes.getSelectedRow();
        Avaliacao aval = this.tableModelAvaliacao.getAvaliacao(linha);
        this.tfId.setText(aval.getId()+"");
        this.tfAvaliador.setText(aval.getAvaliador()+"");
        this.tfTrabalho.setText(aval.getTrabalhoAvaliado()+"");
        this.tfPeriodo.setText(aval.getPeriodo()+"");
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        this.tfDataAvaliacao.setText(aval.getDataAvaliacao().format(dtf));
        this.tfCriterio1.setText(aval.getNotaCriterio1()+"");
        this.tfCriterio2.setText(aval.getNotaCriterio2()+"");
        this.tfCriterio3.setText(aval.getNotaCriterio3()+"");
        this.tfCriterio4.setText(aval.getNotaCriterio4()+"");
        this.tfCriterio5.setText(aval.getNotaCriterio5()+"");
        this.tfCriterio6.setText(aval.getNotaCriterio6()+"");
        this.tfCriterio7.setText(aval.getNotaCriterio7()+"");
        this.tfCriterio8.setText(aval.getNotaCriterio8()+"");
        this.tfCriterio9.setText(aval.getNotaCriterio9()+"");
        this.tfCriterio10.setText(aval.getNotaCriterio10()+"");
        this.tfCriterio11.setText(aval.getNotaCriterio11()+"");
        this.tfCriterio12.setText(aval.getNotaCriterio12()+"");
        this.tfCriterio13.setText(aval.getNotaCriterio13()+"");
        this.tfCriterio14.setText(aval.getNotaCriterio14()+"");
    }//GEN-LAST:event_tabelasAvaliacoesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelId10;
    private javax.swing.JLabel jLabelId11;
    private javax.swing.JLabel jLabelId12;
    private javax.swing.JLabel jLabelId13;
    private javax.swing.JLabel jLabelId14;
    private javax.swing.JLabel jLabelId15;
    private javax.swing.JLabel jLabelId16;
    private javax.swing.JLabel jLabelId18;
    private javax.swing.JLabel jLabelId19;
    private javax.swing.JLabel jLabelId2;
    private javax.swing.JLabel jLabelId3;
    private javax.swing.JLabel jLabelId4;
    private javax.swing.JLabel jLabelId5;
    private javax.swing.JLabel jLabelId6;
    private javax.swing.JLabel jLabelId7;
    private javax.swing.JLabel jLabelId8;
    private javax.swing.JLabel jLabelId9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelasAvaliacoes;
    private javax.swing.JTextField tfAvaliador;
    private javax.swing.JTextField tfCriterio1;
    private javax.swing.JTextField tfCriterio10;
    private javax.swing.JTextField tfCriterio11;
    private javax.swing.JTextField tfCriterio12;
    private javax.swing.JTextField tfCriterio13;
    private javax.swing.JTextField tfCriterio14;
    private javax.swing.JTextField tfCriterio2;
    private javax.swing.JTextField tfCriterio3;
    private javax.swing.JTextField tfCriterio4;
    private javax.swing.JTextField tfCriterio5;
    private javax.swing.JTextField tfCriterio6;
    private javax.swing.JTextField tfCriterio7;
    private javax.swing.JTextField tfCriterio8;
    private javax.swing.JTextField tfCriterio9;
    private javax.swing.JTextField tfDataAvaliacao;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfPeriodo;
    private javax.swing.JTextField tfTrabalho;
    // End of variables declaration//GEN-END:variables
    private Connection connection;
    private AvaliacaoDao avaliacoesDao;
}
