package view;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AvaliadorTrabalho;
import model.AvaliadorTrabalhoDao;
import model.TableModelAvaliadorTrabalho;
import util.TextFieldsUtils;

public class CrudAvaliadorTrabalho extends javax.swing.JInternalFrame {
    private TableModelAvaliadorTrabalho tableModelAvaliadorTrabalho;
    /**
     * Creates new form CrudPessoas
     */
    public CrudAvaliadorTrabalho(Connection con) {
         connection = con;
         avaliadorTrabalhoDao = new AvaliadorTrabalhoDao(con);
        initComponents();
        tableModelAvaliadorTrabalho = new TableModelAvaliadorTrabalho();
        this.tabelaAvaliador.setModel(tableModelAvaliadorTrabalho);
        this.adicionaElementos();
    }
    public void adicionaElementos(){
        List<AvaliadorTrabalho> lsitaAvaliadorTrabalho = avaliadorTrabalhoDao.getLista();
        for (AvaliadorTrabalho avaliadorTrabalho : lsitaAvaliadorTrabalho) {
            tableModelAvaliadorTrabalho.addTrabalho(avaliadorTrabalho);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        jLabelId2 = new javax.swing.JLabel();
        tfNomeAvaliador = new javax.swing.JTextField();
        tfAvaliador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelId6 = new javax.swing.JLabel();
        tfTrabalho = new javax.swing.JTextField();
        jLabelId7 = new javax.swing.JLabel();
        tfNomeTrabalho = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAvaliador = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(240, 240, 250));
        jPanel1.setAutoscrolls(true);

        jLabel9.setBackground(new java.awt.Color(235, 240, 240));
        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Crud AvaliadorTrabalho");

        jLabelId.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId.setText("      ID:");

        tfId.setEditable(false);
        tfId.setText("1");
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabelId1.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId1.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId1.setText("NOME AVALIADOR:");

        jLabelId2.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId2.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId2.setText("AVALIADOR ID:");

        tfNomeAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeAvaliadorActionPerformed(evt);
            }
        });

        tfAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAvaliadorActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jButton4.setText("Fechar");

        jLabelId6.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId6.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId6.setText("TRABALHO ID:");

        tfTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTrabalhoActionPerformed(evt);
            }
        });

        jLabelId7.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId7.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId7.setText("NOME  TRABALHO:");

        tfNomeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeTrabalhoActionPerformed(evt);
            }
        });

        tabelaAvaliador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"423421", "312312", "312321", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaAvaliador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAvaliadorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaAvaliador);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelId6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelId1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeAvaliador))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelId7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAdicionar)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfNomeTrabalho))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnLimpar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfNomeAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeAvaliadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeAvaliadorActionPerformed

    private void tfAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAvaliadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAvaliadorActionPerformed

    private void tfTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTrabalhoActionPerformed

    private void tfNomeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeTrabalhoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        new TextFieldsUtils().clearTextFields(rootPane);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
                                       

        if ((this.tfAvaliador.getText().trim().equals(""))||(this.tfTrabalho.getText().trim().equals(""))) {
            if((this.tfAvaliador.getText().trim().equals(""))&&(this.tfTrabalho.getText().trim().equals(""))){
                JOptionPane.showMessageDialog(this,"Campos vazios");
            }
            else if(this.tfAvaliador.getText().trim().equals("")){
                 JOptionPane.showMessageDialog(this,"Campo Avaliador Vazio");
            }
            else if(this.tfTrabalho.getText().trim().equals("")){
                 JOptionPane.showMessageDialog(this,"Campo Avaliador Vazio");
            }
        } else {
            try {
                AvaliadorTrabalho novoAvaliadorTrabalho = new AvaliadorTrabalho();
                  if(tfId.getText().equals("") == false){
                    novoAvaliadorTrabalho.setId(Long.parseLong(tfId.getText()));
                }
                novoAvaliadorTrabalho.setAvaliador(Integer.parseInt(this.tfAvaliador.getText()));
                novoAvaliadorTrabalho.setTrabalho(Integer.parseInt(this.tfTrabalho.getText()));
                if(avaliadorTrabalhoDao.salvar(novoAvaliadorTrabalho)){
                if(novoAvaliadorTrabalho.getId() == null){
                      novoAvaliadorTrabalho.setId(avaliadorTrabalhoDao.getLista().get(avaliadorTrabalhoDao.getLista().size()-1).getId());
                    tableModelAvaliadorTrabalho.addTrabalho(novoAvaliadorTrabalho);
                }  else { 
                    tableModelAvaliadorTrabalho.edita(novoAvaliadorTrabalho);
                }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor informe numeros válidos");
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(tfId.getText() == ""){
            JOptionPane.showMessageDialog(this, "Id vazio");
        } else{
            if(avaliadorTrabalhoDao.removeAvaliadorTrabalho(Long.parseLong(this.tfId.getText()))){
                tableModelAvaliadorTrabalho.removeAvaliadorTrabalho(tabelaAvaliador.getSelectedRow());
                 new TextFieldsUtils().clearTextFields(rootPane);
            }
            
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tabelaAvaliadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAvaliadorMouseClicked
         int linha = this.tabelaAvaliador.getSelectedRow();
        AvaliadorTrabalho avaliadorTrabalho = this.tableModelAvaliadorTrabalho.getTrabalho(linha);
        this.tfId.setText(""+avaliadorTrabalho.getId());
        this.tfAvaliador.setText(""+avaliadorTrabalho.getAvaliador());
        this.tfTrabalho.setText(""+avaliadorTrabalho.getTrabalho());
    }//GEN-LAST:event_tabelaAvaliadorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelId2;
    private javax.swing.JLabel jLabelId6;
    private javax.swing.JLabel jLabelId7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaAvaliador;
    private javax.swing.JTextField tfAvaliador;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNomeAvaliador;
    private javax.swing.JTextField tfNomeTrabalho;
    private javax.swing.JTextField tfTrabalho;
    // End of variables declaration//GEN-END:variables
    private Connection connection;
    private AvaliadorTrabalhoDao avaliadorTrabalhoDao;
}
