
package view;

import java.math.BigDecimal;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Evento;
import model.EventoDao;
import model.TableModelEvento;
import util.TextFieldsUtils;

public class CrudEventos extends javax.swing.JInternalFrame {

    private TableModelEvento tableModelEvento;
    public CrudEventos(Connection con) {
        connection = con;
        eventoDao = new EventoDao(con);
        initComponents();
        this.tableModelEvento = new TableModelEvento();
        this.tabelaEventos.setModel(tableModelEvento);
        adicionaElementos();
    }
    
    public void adicionaElementos(){
        List<Evento> listaEventos = this.eventoDao.getLista();
        for (Evento evento : listaEventos) {
            tableModelEvento.addEvento(evento);
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        jLabelId2 = new javax.swing.JLabel();
        tfInicio = new javax.swing.JTextField();
        tfAno = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jLabelId4 = new javax.swing.JLabel();
        tfQtdMinima = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabelId6 = new javax.swing.JLabel();
        tfTermino = new javax.swing.JTextField();
        jLabelId8 = new javax.swing.JLabel();
        tfQtdMaxima = new javax.swing.JTextField();
        jLabelId10 = new javax.swing.JLabel();
        jLabelId11 = new javax.swing.JLabel();
        tfNumeroAvaliadores = new javax.swing.JTextField();
        jLabelId12 = new javax.swing.JLabel();
        tfNota = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEventos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(240, 240, 250));
        jPanel1.setAutoscrolls(true);

        jLabel9.setBackground(new java.awt.Color(235, 240, 240));
        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Crud Eventos");

        jLabelId.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId.setText("       ID:");

        tfId.setEditable(false);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabelId1.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId1.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId1.setText("INICIO:");

        jLabelId2.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId2.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId2.setText("ANO:");

        tfInicio.setText("                ");
        tfInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInicioActionPerformed(evt);
            }
        });

        tfAno.setText("       ");
        tfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnoActionPerformed(evt);
            }
        });

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabelId4.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId4.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId4.setText("NOME:");

        tfQtdMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdMinimaActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabelId6.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId6.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId6.setText("TERMINO:");

        tfTermino.setText("              ");
        tfTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTerminoActionPerformed(evt);
            }
        });

        jLabelId8.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId8.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId8.setText("QUANTIDADE MÍNIMA DE INTEGRANTES:");

        tfQtdMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdMaximaActionPerformed(evt);
            }
        });

        jLabelId10.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId10.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId10.setText("QUANTIDADE MÁXIMA DE INTEGRANTES:");

        jLabelId11.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId11.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId11.setText("NUMERO DE AVALIADORES");

        tfNumeroAvaliadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroAvaliadoresActionPerformed(evt);
            }
        });

        jLabelId12.setBackground(new java.awt.Color(235, 240, 235));
        jLabelId12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId12.setForeground(new java.awt.Color(13, 15, 0));
        jLabelId12.setText("NOTA:");

        tfNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNotaActionPerformed(evt);
            }
        });

        tabelaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEventosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaEventos);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelId4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelId10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQtdMaxima))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelId8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQtdMinima))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelId)
                                .addComponent(jLabelId1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelId6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelId11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumeroAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelId12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNota))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNumeroAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnLimpar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeletar)
                        .addComponent(btnFechar))
                    .addComponent(btnAtualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNotaActionPerformed

    private void tfNumeroAvaliadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroAvaliadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroAvaliadoresActionPerformed

    private void tfQtdMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdMaximaActionPerformed

    private void tfTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTerminoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tfQtdMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdMinimaActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnoActionPerformed

    private void tfInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInicioActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        new TextFieldsUtils().clearTextFields(rootPane);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        List <String> strings = new ArrayList<String>();
       new TextFieldsUtils().getTfs(rootPane, strings);
        if (new TextFieldsUtils().verificandoVazios(strings)) {
            JOptionPane.showMessageDialog(this, "Campos vazios");
        } else {
            try {
               Evento novoEvento = new Evento();
               if(tfId.getText().equals("") == false){
                    novoEvento.setId(Long.parseLong(tfId.getText()));
                }
               DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
               novoEvento.setAno(Integer.parseInt(this.tfAno.getText()));
               novoEvento.setDataInicio(LocalDate.parse(this.tfInicio.getText(),dtf));
               novoEvento.setDataTermino(LocalDate.parse(this.tfTermino.getText(),dtf));
               novoEvento.setNome(this.tfNome.getText());
               novoEvento.setNotaAtribuida(new BigDecimal(this.tfNota.getText()));
               novoEvento.setNumeroDeAvaliadores(Integer.parseInt(this.tfNumeroAvaliadores.getText()));
               novoEvento.setQuantidadeMaximaTrabalho(Integer.parseInt(this.tfQtdMaxima.getText()));
               novoEvento.setQuantidadeMinimaTrabalho(Integer.parseInt(this.tfQtdMinima.getText()));
               if(eventoDao.salvar(novoEvento)){
                if(novoEvento.getId() == null){
                     novoEvento.setId(eventoDao.getLista().get(eventoDao.getLista().size()-1).getId());
                    tableModelEvento.addEvento(novoEvento);
                }  else { 
                    tableModelEvento.edita(novoEvento);
                }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valores Inválidos");
            } catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(this,"Formato de data inválido, informe DD/MM/YYYY");
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(tfId.getText() == ""){
            JOptionPane.showMessageDialog(this, "Id vazio");
        } else{
            if(eventoDao.removeEvento(Long.parseLong(this.tfId.getText()))){
                tableModelEvento.removerEvento(tabelaEventos.getSelectedRow());
                 new TextFieldsUtils().clearTextFields(rootPane);
            }
            
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tabelaEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEventosMouseClicked
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
         int linha = this.tabelaEventos.getSelectedRow();
        Evento evento = this.tableModelEvento.getEvento(linha);
        this.tfId.setText(""+evento.getId());;
        this.tfNome.setText(""+evento.getNome());
        this.tfAno.setText(""+evento.getAno());
        this.tfNota.setText(""+evento.getNotaAtribuida());
        this.tfNumeroAvaliadores.setText(""+evento.getNumeroDeAvaliadores());
        this.tfQtdMaxima.setText(""+evento.getQuantidadeMaximaTrabalho());
        this.tfQtdMinima.setText(""+evento.getQuantidadeMinimaTrabalho());
        this.tfInicio.setText(""+evento.getDataInicio().format(dtf));
        this.tfTermino.setText(""+evento.getDataTermino().format(dtf));
    }//GEN-LAST:event_tabelaEventosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelId10;
    private javax.swing.JLabel jLabelId11;
    private javax.swing.JLabel jLabelId12;
    private javax.swing.JLabel jLabelId2;
    private javax.swing.JLabel jLabelId4;
    private javax.swing.JLabel jLabelId6;
    private javax.swing.JLabel jLabelId8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaEventos;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfInicio;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNota;
    private javax.swing.JTextField tfNumeroAvaliadores;
    private javax.swing.JTextField tfQtdMaxima;
    private javax.swing.JTextField tfQtdMinima;
    private javax.swing.JTextField tfTermino;
    // End of variables declaration//GEN-END:variables
    private Connection connection;
    private EventoDao eventoDao;
}
