package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;
import model.Pessoa;
import model.PessoaDao;

public class TelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form crudPessoa
     */
    public TelaAdmin(Pessoa admin, Connection con) {
        connection = con;
        pessoaLogada = admin;
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Adminstrador");
        this.customizeMenuBar(barraMenus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenus = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCruds = new javax.swing.JMenu();
        miEventos = new javax.swing.JMenuItem();
        miPessoas = new javax.swing.JMenuItem();
        miAlunos = new javax.swing.JMenuItem();
        miTrabalhos = new javax.swing.JMenuItem();
        miAvaliador = new javax.swing.JMenuItem();
        miAvaliacoes = new javax.swing.JMenuItem();
        menuVinculacoes = new javax.swing.JMenu();
        miVincAlunoTrabalho = new javax.swing.JMenuItem();
        miVincPessoaTrabalho = new javax.swing.JMenuItem();
        menuNota = new javax.swing.JMenu();
        miGerarNota = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        miRelatorio1 = new javax.swing.JMenuItem();
        miRelatorio2 = new javax.swing.JMenuItem();
        miRelatorio3 = new javax.swing.JMenuItem();
        miRelatorio4 = new javax.swing.JMenuItem();
        miRelatorio5 = new javax.swing.JMenuItem();
        miRelatorio6 = new javax.swing.JMenuItem();
        menuTrocarSenha = new javax.swing.JMenu();
        miTrocarSenha = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        miDesconectar = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 230, 230));
        setIconImage(new ImageIcon(getClass().getResource("../icons/iftm.jpg")).getImage());
        setPreferredSize(new java.awt.Dimension(1250, 650));
        setResizable(false);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1202, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        barraMenus.setForeground(new java.awt.Color(255, 255, 255));
        barraMenus.setMinimumSize(new java.awt.Dimension(30, 40));
        barraMenus.add(jMenu1);

        menuCruds.setText("CRUDs");

        miEventos.setText("Eventos");
        miEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEventosActionPerformed(evt);
            }
        });
        menuCruds.add(miEventos);

        miPessoas.setText("Pessoas");
        miPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoasActionPerformed(evt);
            }
        });
        menuCruds.add(miPessoas);

        miAlunos.setText("Alunos");
        miAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlunosActionPerformed(evt);
            }
        });
        menuCruds.add(miAlunos);

        miTrabalhos.setText("Trabalhos");
        miTrabalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTrabalhosActionPerformed(evt);
            }
        });
        menuCruds.add(miTrabalhos);

        miAvaliador.setText("Avaliador-Trabalho");
        miAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAvaliadorActionPerformed(evt);
            }
        });
        menuCruds.add(miAvaliador);

        miAvaliacoes.setText("Avaliações");
        miAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAvaliacoesActionPerformed(evt);
            }
        });
        menuCruds.add(miAvaliacoes);

        barraMenus.add(menuCruds);

        menuVinculacoes.setText("Vinculações");

        miVincAlunoTrabalho.setText("Vinc Aluno/Trabalho");
        miVincAlunoTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVincAlunoTrabalhoActionPerformed(evt);
            }
        });
        menuVinculacoes.add(miVincAlunoTrabalho);

        miVincPessoaTrabalho.setText("Vinc Pessoa/Trabalho");
        miVincPessoaTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVincPessoaTrabalhoActionPerformed(evt);
            }
        });
        menuVinculacoes.add(miVincPessoaTrabalho);

        barraMenus.add(menuVinculacoes);

        menuNota.setText("Gerar Nota");

        miGerarNota.setText("Nota Final");
        miGerarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerarNotaActionPerformed(evt);
            }
        });
        menuNota.add(miGerarNota);

        barraMenus.add(menuNota);

        menuRelatorio.setText("Relatórios");

        miRelatorio1.setText("Gerar Relatório (1)");
        miRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorio1ActionPerformed(evt);
            }
        });
        menuRelatorio.add(miRelatorio1);

        miRelatorio2.setText("Gerar Relatório (2)");
        menuRelatorio.add(miRelatorio2);

        miRelatorio3.setText("Gerar Relatório (3)");
        miRelatorio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorio3ActionPerformed(evt);
            }
        });
        menuRelatorio.add(miRelatorio3);

        miRelatorio4.setText("Gerar Relatório (4)");
        menuRelatorio.add(miRelatorio4);

        miRelatorio5.setText("Gerar Relatório (5)");
        miRelatorio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorio5ActionPerformed(evt);
            }
        });
        menuRelatorio.add(miRelatorio5);

        miRelatorio6.setText("Gerar Relatório (6)");
        menuRelatorio.add(miRelatorio6);

        barraMenus.add(menuRelatorio);

        menuTrocarSenha.setText("Trocar Senha");

        miTrocarSenha.setText("Trocar Senha");
        miTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTrocarSenhaActionPerformed(evt);
            }
        });
        menuTrocarSenha.add(miTrocarSenha);

        barraMenus.add(menuTrocarSenha);

        menuSair.setText("Sair");

        miDesconectar.setText("Desconectar");
        miDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDesconectarActionPerformed(evt);
            }
        });
        menuSair.add(miDesconectar);

        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        menuSair.add(miSair);

        barraMenus.add(menuSair);

        setJMenuBar(barraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoasActionPerformed
        desktop.removeAll();
        crudPessoas = new CrudPessoas(connection);
        crudPessoas.setVisible(true);
        desktop.add(crudPessoas);

    }//GEN-LAST:event_miPessoasActionPerformed

    private void miAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlunosActionPerformed
        desktop.removeAll();
        crudAlunos = new CrudAlunos(connection);
        crudAlunos.setVisible(true);
        desktop.add(crudAlunos);
    }//GEN-LAST:event_miAlunosActionPerformed

    private void miAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAvaliadorActionPerformed
        desktop.removeAll();
        crudAvaliadorTrabalho = new CrudAvaliadorTrabalho(connection);
        crudAvaliadorTrabalho.setVisible(true);
        desktop.add(crudAvaliadorTrabalho);
    }//GEN-LAST:event_miAvaliadorActionPerformed

    private void miRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorio1ActionPerformed

    }//GEN-LAST:event_miRelatorio1ActionPerformed

    private void miRelatorio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miRelatorio5ActionPerformed

    private void miGerarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miGerarNotaActionPerformed

    private void miRelatorio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miRelatorio3ActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSairActionPerformed

    private void miTrabalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTrabalhosActionPerformed
        desktop.removeAll();
        crudTrabalhos = new CrudTrabalhos(connection);
        crudTrabalhos.setVisible(true);
        desktop.add(crudTrabalhos);
    }//GEN-LAST:event_miTrabalhosActionPerformed

    private void miEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEventosActionPerformed
        desktop.removeAll();
        crudEventos = new CrudEventos(connection);
        crudEventos.setVisible(true);
        desktop.add(crudEventos);
    }//GEN-LAST:event_miEventosActionPerformed

    private void miAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAvaliacoesActionPerformed
        desktop.removeAll();
        crudAvaliacoes = new CrudAvaliacoes(connection);
        crudAvaliacoes.setVisible(true);
        desktop.add(crudAvaliacoes);
    }//GEN-LAST:event_miAvaliacoesActionPerformed

    private void miTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTrocarSenhaActionPerformed
        this.changePassword = new ChangePassword(this, true, connection, pessoaLogada);
        this.changePassword.setVisible(true);
    }//GEN-LAST:event_miTrocarSenhaActionPerformed

    private void miVincAlunoTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVincAlunoTrabalhoActionPerformed
        vincAlunoTrabalho = new VincAlunoTrabalho(this, true);
        vincAlunoTrabalho.setVisible(true);
    }//GEN-LAST:event_miVincAlunoTrabalhoActionPerformed

    private void miVincPessoaTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVincPessoaTrabalhoActionPerformed
        vincAvaliadorTrabalho = new VincAvaliadorTrabalho(this, true);
        vincAvaliadorTrabalho.setVisible(true);
    }//GEN-LAST:event_miVincPessoaTrabalhoActionPerformed

    private void miDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDesconectarActionPerformed

        new LoginMTEC().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miDesconectarActionPerformed

    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(47, 130, 55));
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(new Color(47, 135, 55));
        comp.setForeground(new Color(250, 250, 225));
        comp.setFont(new Font("Monaco", Font.PLAIN, 16));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuCruds;
    private javax.swing.JMenu menuNota;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuTrocarSenha;
    private javax.swing.JMenu menuVinculacoes;
    private javax.swing.JMenuItem miAlunos;
    private javax.swing.JMenuItem miAvaliacoes;
    private javax.swing.JMenuItem miAvaliador;
    private javax.swing.JMenuItem miDesconectar;
    private javax.swing.JMenuItem miEventos;
    private javax.swing.JMenuItem miGerarNota;
    private javax.swing.JMenuItem miPessoas;
    private javax.swing.JMenuItem miRelatorio1;
    private javax.swing.JMenuItem miRelatorio2;
    private javax.swing.JMenuItem miRelatorio3;
    private javax.swing.JMenuItem miRelatorio4;
    private javax.swing.JMenuItem miRelatorio5;
    private javax.swing.JMenuItem miRelatorio6;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miTrabalhos;
    private javax.swing.JMenuItem miTrocarSenha;
    private javax.swing.JMenuItem miVincAlunoTrabalho;
    private javax.swing.JMenuItem miVincPessoaTrabalho;
    // End of variables declaration//GEN-END:variables
    private CrudPessoas crudPessoas;
    private CrudAlunos crudAlunos;
    private CrudEventos crudEventos;
    private CrudTrabalhos crudTrabalhos;
    private CrudAvaliacoes crudAvaliacoes;
    private CrudAvaliadorTrabalho crudAvaliadorTrabalho;
    private ChangePassword changePassword;
    private VincAlunoTrabalho vincAlunoTrabalho;
    private VincAvaliadorTrabalho vincAvaliadorTrabalho;
    private Connection connection;
    private Pessoa pessoaLogada;

    /* private CrudAlunos crudAlunos; private CrudEventos crudEventos; private CrudTrabalhos crudTrabalhos; private CrudAlunos crudAlunos;
       private CrudAvaliadorTrabalho crudAvaliador;
     */

    public Connection getConnection() {
        return connection;
    }

    public Pessoa getPessoaLogada() {
        return pessoaLogada;
    }

}
