package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;
import model.Pessoa;

public class TelaPessoa extends javax.swing.JFrame {

    /**
     * Creates new form crudPessoa
     */
    public TelaPessoa(Pessoa pessoa, Connection con) {
        connection = con;
        pessoaLogada = pessoa;
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Avaliador");
        this.customizeMenuBar(barraMenus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem17 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        barraMenus = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVinculacoes = new javax.swing.JMenu();
        miLançarNotas = new javax.swing.JMenuItem();
        menuPenalizacao = new javax.swing.JMenu();
        miLançarPenalizacao = new javax.swing.JMenuItem();
        menuNota = new javax.swing.JMenu();
        miTrocarSenha = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        miDesconectar = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();

        jMenuItem17.setText("jMenuItem17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 230, 230));
        setIconImage(new ImageIcon(getClass().getResource("../icons/iftm.jpg")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        barraMenus.setBackground(new java.awt.Color(240, 240, 250));
        barraMenus.setForeground(new java.awt.Color(255, 255, 255));
        barraMenus.setMinimumSize(new java.awt.Dimension(30, 40));
        barraMenus.add(jMenu1);

        menuVinculacoes.setText("Lançar Notas");

        miLançarNotas.setText("Trabalhos Vinculados");
        miLançarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLançarNotasActionPerformed(evt);
            }
        });
        menuVinculacoes.add(miLançarNotas);

        barraMenus.add(menuVinculacoes);

        menuPenalizacao.setText("Lançar Penalizações");

        miLançarPenalizacao.setText("Lançar penalização");
        miLançarPenalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLançarPenalizacaoActionPerformed(evt);
            }
        });
        menuPenalizacao.add(miLançarPenalizacao);

        barraMenus.add(menuPenalizacao);

        menuNota.setText("Perfil");

        miTrocarSenha.setText("Trocar senha");
        miTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTrocarSenhaActionPerformed(evt);
            }
        });
        menuNota.add(miTrocarSenha);

        barraMenus.add(menuNota);

        menuSair.setText("Sair");

        miDesconectar.setText("Desconectar");
        miDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDesconectarActionPerformed(evt);
            }
        });
        menuSair.add(miDesconectar);

        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        menuSair.add(miSair);

        barraMenus.add(menuSair);

        setJMenuBar(barraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTrocarSenhaActionPerformed
        this.changePassword = new ChangePassword(this, true, connection, pessoaLogada);
        this.changePassword.setVisible(true);
    }//GEN-LAST:event_miTrocarSenhaActionPerformed

    private void miLançarPenalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLançarPenalizacaoActionPerformed
        this.lancarPenalizacao = new LancarPenalizacao(this, true);
        this.lancarPenalizacao.setVisible(true);
        //this.lancarPenalizacao.setLocationRelativeTo(this);
    }//GEN-LAST:event_miLançarPenalizacaoActionPerformed

    private void miLançarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLançarNotasActionPerformed
        this.lancarNotas = new LancarNotas(this, true);
        this.lancarNotas.setVisible(true);
        //this.lancarNotas.setLocationRelativeTo(null);
    }//GEN-LAST:event_miLançarNotasActionPerformed

    private void miDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDesconectarActionPerformed
        new LoginMTEC().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miDesconectarActionPerformed

    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(47, 135, 55));
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(new Color(47, 130, 55));
        comp.setForeground(new Color(250, 250, 225));
        comp.setFont(new Font("Monaco", Font.PLAIN, 16));
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuNota;
    private javax.swing.JMenu menuPenalizacao;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVinculacoes;
    private javax.swing.JMenuItem miDesconectar;
    private javax.swing.JMenuItem miLançarNotas;
    private javax.swing.JMenuItem miLançarPenalizacao;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miTrocarSenha;
    // End of variables declaration//GEN-END:variables
    private ChangePassword changePassword;
    private LancarNotas lancarNotas;
    private LancarPenalizacao lancarPenalizacao;
    private Connection connection;
    private Pessoa pessoaLogada;

    public Connection getConnection() {
        return connection;
    }

    public Pessoa getPessoaLogada() {
        return pessoaLogada;
    }

}
